#!/bin/bash

check-git-user-email() {
  cd "$1" || return
  printf "user.email = %-25s (%s)\n" "$(git config user.email)" "$1"
  cd /Users/jaheath/Development || return
}

find . -type d -mindepth 2 -maxdepth 2 | while read -r line
do 
  dir=${line:2}
  check-git-user-email "$dir"; 
done

