#!/bin/bash

check-git-status() {
  cd "$1" || return
  printf -- "------------------------------------------------------------------------\n"
  printf -- "-- %s\n" "$1"
  printf -- "------------------------------------------------------------------------\n"
  git status
  printf "\n\n"

  cd /Users/jaheath/Development || return
}


find . -type d -mindepth 2 -maxdepth 2 | while read -r line
do 
  dir=${line:2}
  check-git-status "$dir"; 
done

