#!/bin/bash

OVERLAY_DIR=$1
if [ -z "$OVERLAY_DIR" ]; then
    echo "OVERLAY_DIR is unset or empty"
    exit
fi


# list modified files
declare -a modified_files
modified_files=( $(git ls-files --modified) )
#echo ${modified_files[*]}
if [ ${#modified_files[*]} -eq 0 ]; then
    echo "No files modified in this git repo"
else
    for x in ${modified_files[*]}; do
        /bin/cp -f $x $OVERLAY_DIR/$x
    done
fi

# # list files that have been deleted
# read -ra a < <(git ls-files --deleted)
# if [ ${#a[@]} -eq 0 ]; then
#     echo "No files deleted in this git repo"
# else
#     for x in ${a[*]}; do
#         echo "$x was deleted but there is no supporting action"
#     done
# fi
#
# # list files that are untracked minus what git ignore "would mask"
# read -ra a < <(git ls-files --others --exclude-standard )
# if [ ${#a[@]} -eq 0 ]; then
#     echo "No untracked in this git repo"
# else
#     for x in ${a[*]}; do
#         echo "$x is untracked but there is no supporting action"
#     done
# fi
